baseURL = "https://KIN325R.adrienbabet.com/"
languageCode = "en-us"
title = "Tissue Inj. & Adapt."
theme = "hextra"

[module]
ignoreFiles = ["themes/hextra/static/*"]

[params]
  [params.navbar]
    displayTitle = true
    displayLogo = true

    [params.navbar.logo]
      path = "custom-favicon.svg"
      dark = "custom-favicon-dark.svg"
      link = "/"
      width = 40
  [params.footer]
    displayPoweredBy = false
    displayCopyright = false
    poweredBy = "© 2025 adrienbabet.com"

[[menu.main]]
name = "Search"
weight = 3
[menu.main.params]
type = "search"
